# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='Task', max_length=140)),
                ('description', models.CharField(max_length=10000)),
                ('creation_date', models.DateTimeField(verbose_name='date task was created')),
                ('deadline', models.DateTimeField(verbose_name='date task is scheduled to be completed')),
                ('additional_notes', models.CharField(max_length=20000)),
                ('priority', models.CharField(choices=[(1, 'High'), (0, 'Normal'), (-1, 'Low')], default=0, max_length=6)),
            ],
        ),
    ]
