# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default={'not completed': False}),
        ),
        migrations.AlterField(
            model_name='task',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('h', 'High'), ('n', 'Normal'), ('l', 'Low')], default='n', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=140),
        ),
    ]
