# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160114_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='not_completed',
            field=models.BooleanField(default=True),
        ),
    ]
