# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20160114_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='not_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
